baseurl = "https://zhaohuabing.com"
title = "Bean Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "bean-4"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/ciat.jpg"
  SEOTitle = "Bean Blog"
  description = "Bean program"
  keyword = "statistic, Bean, CIAT, Bioinformatics , data, agriculture"
  slogan = "International Center for Tropical Agriculture"

  image_404 = "img/404-bg.jpg"
  title_404 = "Error :("

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = "V0DMRF62ZX"
  algolia_indexName = "blog"
  algolia_apiKey = "02822e760a5e0760f84d586b030fa1dc"

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/team.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  #disqus_proxy = ""
  #disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "" 

  friends = false
  bookmarks = true
  about_me = true

  [params.social]
  rss            = false 
  email          = "J.aparicio@cgiar.org"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter        = "https://twitter.com/CIAT_?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"
  linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
#  stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/beanciat/"
#  wechat         = "your wechat qr code image"
#  medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "CIAT"
  href =  "https://ciat.cgiar.org/"

  [[params.bookmark_link]]
  title =  "CIAT"
  href =  "https://ciat.cgiar.org/"
  [[params.bookmark_link]]
  title =  "MrBean"
  href =  "https://apariciojohan.shinyapps.io/Mrbean/"
  
  [[params.addtional_menus]]
  title =  "BOOKS"
  href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

